const data=[
    {
        name:"gael",
        image:require('../../assets/gael.jpg'),
        sicknesType:'malaria',
        address:'douala'
    },
    {
        name:"cypher",
        image:require('../../assets/1.png'),
        sicknesType:'eye',
        address:'douala'
    },
    {
        name:"hohn",
        image:require('../../assets/2.png'),
        sicknesType:'malaria',
        address:'bamabili'
    },
    {
        name:"emma",
        image:require('../../assets/3.png'),
        sicknesType:'malaria',
        address:'buea'
    },
    {
        name:"mary",
        image:require('../../assets/gael.jpg'),
        sicknesType:'malaria',
        address:'bamenda'
    },
    {
        name:"peter",
        image:require('../../assets/2.png'),
        sicknesType:'malaria',
        address:'yde'
    },
]
export default data