export default data =[
    {
        name:'Tramadol',
        number:12,
        dose:2+'morning'+2+"evening",
        gram:'2gm',
        image:require('../../../assets/2.png')
    },
    {
        name:'paracetamol',
        number:12,
        dose:2+'morning'+2+"evening",
        gram:'2gm',
        image:require('../../../assets/1.png')
    },
    {
        name:'indocine',
        number:12,
        dose:2+'morning'+2+"evening",
        gram:'2gm',
        image:require('../../../assets/3.png')
    },
]